baseURL : "http://localhost:1313/"
languageCode : "zh-CN"
title : "ğŸ˜ª"
theme : "hugo-theme-cactus-dark"
permalinks:
  archive: archive/:slug/
params:
  Author: djkloop
  description: ä¸€ä¸ªå‰ç«¯æŠ€æœ¯åšå®¢.æ¯å¤©ç¢°åˆ°é‚£ä¹ˆå¤šé—®é¢˜, ç»ˆå½’è¿˜æ˜¯éœ€è¦ä¸€ä¸ªè®°å½•çš„åœ°æ–¹.
  keywords: [djkloop, å‰ç«¯çˆ±å¥½è€…, å‰ç«¯å¼€å‘, webå‰ç«¯åšå®¢, js, html5, css, Vue.js, React.js, Angular.js, node.js]
  _theme: "hugo-theme-cactus-dark"
  github:
    author: 'djkloop'
    url: 'https://github.com/djkloop'
  customize:
    logo:
        enable: true
        width: 50
        height: 50
        url: /images/logo2.png
        gravatar: false


