baseURL : "http://localhost:1313/"
languageCode : "zh-CN"
title : "ğŸ˜ª"
theme : "hugo-theme-cactus-dark"
permalinks:
  archive: archive/:slug/
params:
  Author: djkloop
  description: ä¸€ä¸ªå‰ç«¯æŠ€æœ¯åšå®¢.æ¯å¤©ç¢°åˆ°é‚£ä¹ˆå¤šé—®é¢˜, ç»ˆå½’è¿˜æ˜¯éœ€è¦ä¸€ä¸ªè®°å½•çš„åœ°æ–¹.
  keywords: [djkloop, å‰ç«¯çˆ±å¥½è€…, å‰ç«¯å¼€å‘, webå‰ç«¯åšå®¢, js, html5, css, Vue.js, React.js, Angular.js, node.js]
  _theme: "hugo-theme-cactus-dark"

  powered:
    enable: true
    url: "https://gohugo.io/"
    cli: "Hugo"

  github:
    author: 'djkloop'
    url: 'https://github.com/djkloop'

  customize:
    # Customize the logo (i.e., the cactus) in the header.
    # Options:
    #   - enabled: whether to show (true) or hide (false) the logo.
    #   - width: width of the logo in pixel units
    #   - height: height of the logo in pixel units
    #   - url: where the logo can be found
    #   - gravatar: whether to use your Gravatar as the logo
    logo:
        enable: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false

    # https://valine.js.org/quickstart.html
    valine:
      enable: true
      LeanCloudAppID: "db74NGgiUiGT5HkLTBoDK7Tl-gzGzoHsz"  # å¡«å†™è‡ªå·±çš„leanCloudAppId
      LeanCloudAppKey: "ApR14unweK4ln7MlK4yDGn63" # å¡«å†™è‡ªå·±çš„leanCloudAppKey
      notify: false
      verify: false
      avatar: 'mp'
      placeholder: 'just go go'

    # Links to your social media accounts.
    # The keys should correspond to Fontawesome icon names
    # (see https://fontawesome.com/icons?d=gallery&s=brands);
    # only 'mail' is an exception.
    social_links:
      github: http://github.com/probberechts/cactus-dark
      twitter: /
      facebook-square: /
      linkedin: /
      email: mailto:name@email.com

    # Link to a page that gives an overview of all your projects.
    # This can be an external link (e.g., to you GitHub profile) or to another
    # page within your website.
    projects_url: http://github.com/djkloop


